import Foundation

// MARK: - Design Overview
//
// ProviderContract is the single resolved source of truth for provider behavior at runtime.
// It combines ProviderMetadata from provider_config.json with protocol defaults via
// field-level merging, so services never need to piece together provider behavior themselves.
//
// Key design decisions:
// - JSON defines "what" (declarative strategy names, patterns, actions).
// - Swift interprets "how" (ReasoningStrategy → ReasoningParams, DisableOverride → action).
// - Field-level merge: provider overrides inherit missing fields from defaults.
// - Explicit null: a JSON null means "disable this feature" and overrides the default.
// - Unknown/custom providers fall back to OpenAI-compatible defaults.
//
// Usage:
//   let contract = providerRegistry.getContract(for: "deepseek")
//   let params = ReasoningConfigBuilder.build(contract: contract, modelId: "deepseek-chat", effort: "high")

// MARK: - Configuration Errors

/// Errors surfaced when loading or validating provider_config.json.
enum ProviderConfigError: LocalizedError {
    case fileNotFound
    case invalidJSON(Error)
    case duplicateProviderId(String)
    case unsupportedEndpointType(provider: String, value: String)
    case unsupportedReasoningStrategy(provider: String, strategy: String)

    var errorDescription: String? {
        switch self {
        case .fileNotFound:
            return L10n.string("provider_config.file_not_found")
        case .invalidJSON(let error):
            return L10n.format("provider_config.invalid_json_format", error.localizedDescription)
        case .duplicateProviderId(let id):
            return L10n.format("provider_config.duplicate_provider_id_format", id)
        case .unsupportedEndpointType(let provider, let value):
            return L10n.format("provider_config.unsupported_endpoint_type_format", provider, value)
        case .unsupportedReasoningStrategy(let provider, let strategy):
            return L10n.format("provider_config.unsupported_reasoning_strategy_format", provider, strategy)
        }
    }
}

// MARK: - Endpoint Contract

/// Identifies the HTTP adapter used to construct requests for an endpoint.
enum EndpointAdapterKind: String, Codable {
    /// OpenAI-compatible `/v1/chat/completions` protocol.
    case openAICompatible = "openai_compatible"
    /// Anthropic Messages API protocol.
    case anthropicMessages = "anthropic_messages"
}

/// Resolved endpoint behavior for a single endpoint type (e.g. OpenAI or Anthropic).
/// Each provider may support one or both endpoint types with different URLs and adapters.
struct ProviderEndpointContract {
    let type: EndpointType
    let adapterKind: EndpointAdapterKind
    let defaultBaseURL: String
    let urlNormalization: URLNormalizationRule
    /// Suffixes to strip from user-provided custom URLs (e.g. `/chat/completions`).
    let stripSuffixes: [String]
}

// MARK: - Capability Contract

/// Strategy for inferring model capabilities (web search, reasoning, tool calling, vision).
enum CapabilityInferenceStrategy: String, Codable {
    /// Prefer API-declared capabilities from `/v1/models`, fall back to regex rules.
    case apiDeclaredThenRules = "api_declared_then_rules"
    /// Use only regex rules from model_capability_rules.json.
    case rulesOnly = "rules_only"
    /// Skip inference entirely; assume no capabilities.
    case none
}

struct ProviderCapabilityContract {
    let strategy: CapabilityInferenceStrategy

    static let openAICompatibleDefault = ProviderCapabilityContract(strategy: .apiDeclaredThenRules)
}

// MARK: - Reasoning Contract

/// Resolved reasoning configuration: the strategy name (from JSON) and its parsed form.
struct ProviderReasoningContract {
    let strategyName: String
    let strategy: ReasoningStrategy?
}

// MARK: - Provider Contract

/// The single resolved entry point for all provider behavior.
///
/// Generated by `ProviderRegistry` from `provider_config.json` + protocol defaults
/// via field-level merging. Services read this contract instead of assembling provider
/// behavior from scattered sources (ProviderMetadata, ProtocolConfig, BaseURLResolver, etc.).
///
/// ## Field-level merging
///
/// When a provider overrides protocol defaults, fields are merged individually:
/// - **Missing fields**: inherit from protocol defaults.
/// - **Explicit null** (via `NullableCodable`): disable the feature, overriding the default.
/// - **Present values**: override the default for that field only.
///
/// Example: MiniMax overrides `streamOptions: null` and `extraFields`, but inherits
/// `stream: true` and `temperatureRange` from defaults.
///
/// ## Custom providers (NewAPI)
///
/// The `newapi` contract is built into the registry with `isCustom: true` and an empty
/// `defaultBaseURL`. User-provided URLs are resolved at call time. Unknown provider IDs
/// fall back to `ProviderContract.openAICompatibleDefault`.
struct ProviderContract {
    let id: String
    let name: String
    let category: APIType
    /// `true` for user-custom providers like NewAPI that accept arbitrary base URLs.
    let isCustom: Bool
    /// The default base URL before endpoint-specific resolution.
    let defaultBaseURL: String
    let defaultEndpointType: EndpointType
    /// All supported endpoints keyed by EndpointType.
    let endpoints: [EndpointType: ProviderEndpointContract]
    /// Request configuration (stream, temperature range, extra fields).
    let request: RequestConfig?
    /// Response parsing configuration (SSE prefix, termination signal, thinking fields, etc.).
    let response: ResponseParserConfig?
    /// Message assembly configuration (tool call handling, reasoning content, system message).
    let messageAssembly: MessageAssemblyConfig?
    /// Merged protocol configuration that services consume directly.
    let protocolConfig: ProtocolConfig
    /// Reasoning strategy for this provider.
    let reasoning: ProviderReasoningContract
    /// Model capability inference strategy.
    let capability: ProviderCapabilityContract

    /// Returns the endpoint contract for `type`, falling back to `defaultEndpointType`,
    /// then to a hardcoded OpenAI default.
    func endpoint(_ type: EndpointType) -> ProviderEndpointContract {
        endpoints[type] ?? endpoints[defaultEndpointType] ?? ProviderContract.defaultOpenAIEndpoint
    }

    func supportsEndpointType(_ type: EndpointType) -> Bool {
        endpoints[type] != nil
    }

    static let defaultOpenAIEndpoint = ProviderEndpointContract(
        type: .openai,
        adapterKind: .openAICompatible,
        defaultBaseURL: "https://api.openai.com/v1",
        urlNormalization: URLNormalizationRule(appendVersion: true, versionPath: "/v1"),
        stripSuffixes: ["/chat/completions"]
    )

    /// Fallback contract for unknown or custom providers.
    static var openAICompatibleDefault: ProviderContract {
        let protocolConfig = ProtocolConfig.openAICompatibleDefaults
        return ProviderContract(
            id: "openai-default",
            name: "OpenAI Compatible",
            category: .openAI,
            isCustom: true,
            defaultBaseURL: defaultOpenAIEndpoint.defaultBaseURL,
            defaultEndpointType: .openai,
            endpoints: [.openai: defaultOpenAIEndpoint],
            request: protocolConfig.request,
            response: protocolConfig.response,
            messageAssembly: protocolConfig.messageAssembly,
            protocolConfig: protocolConfig,
            reasoning: ProviderReasoningContract(
                strategyName: "openai-standard",
                strategy: ReasoningStrategy.openAIStandard
            ),
            capability: .openAICompatibleDefault
        )
    }
}
